require_relative '../app/usecases/usecase/create_comment'
require_relative '../app/entities/comment_entity'
require_relative '../app/validators/validator/comment_validator'
require_relative '../app/policies/policy/user/can_create_comment'
require_relative '../app/usecases/usecase/create_comment'